name: CI-MainEntryRoute
on:
  workflow_call:
    inputs:
      path:
        required: false
        default: './Reports/${{ vars.TARGET_WORKSPACE_NAME }}'
        type: string
      filePattern:
        required: false
        default: './Reports/${{ vars.TARGET_WORKSPACE_NAME }}/*.pbix'
        type: string
      workspacename:
        required: false
        default: '${{ vars.TARGET_WORKSPACE_NAME }}'
        type: string
## commenting out below section as applicable for multi workspace publish##
    #  path1:
     #   required: false
      #  default: './Reports/LM'
       # type: string
      # filePattern1:
       # required: false
        # default: './Reports/LM/*.pbix'
        # type: string
      # workspacename1:
       # required: false
        # default: 'TEST_LM'
        # type: string
## commenting out above section as applicable for multi workspace publish##

    secrets:
      clientid:
        required: true
      secret:
        required: true
      tenantid:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish PBI contents for Workspace ${{ vars.TARGET_WORKSPACE_NAME }}
        shell: powershell
        run: |
          Get-ChildItem ${{ inputs.filePattern }}
          ./GitHub/run-task.ps1 -ClientId ${{ secrets.clientid }} -Secret ${{ secrets.secret }} -TenantId ${{ secrets.tenantid }} -FilePattern ${{ inputs.filePattern}} -WorkspaceName ${{ inputs.workspacename }} -Action 'Publish' -Create $false -Overwrite $true
# commenting out below section as applicable for multi workspace publish ###
     # - name: Call the PS script and publish PBI contents for LM
      #  shell: powershell
       # run: |
        #  Get-ChildItem ${{ inputs.filePattern1 }}
         # ./GitHub/run-task.ps1 -ClientId ${{ secrets.clientid }} -Secret ${{ secrets.secret }} -TenantId ${{ secrets.tenantid }} -FilePattern ${{ inputs.filePattern1}} -WorkspaceName ${{ inputs.workspacename1 }} -Action 'Publish' -Create $false -Overwrite $true
## commenting out above section as applicable for multi workspace publish##
