name: CI-MainEntryRoute
on:
  workflow_call:
    inputs:
      path:
        required: false
        default: './Reports/${{ vars.TARGET_WORKSPACE_NAME }}'
        type: string
      filePattern:
        required: false
        default: './Reports/${{ vars.TARGET_WORKSPACE_NAME }}/*.pbix'
        type: string
      workspacename:
        required: false
        default: '${{ vars.TARGET_WORKSPACE_NAME }}'
        type: string

    secrets:
      clientid:
        required: true
      secret:
        required: true
      tenantid:
        required: true

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install from PSGallery
        shell: powershell
        run: |
          ./GitHub/install.ps

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish PBI contents for Workspace ${{ vars.TARGET_WORKSPACE_NAME }}
        shell: powershell
        run: |
          Get-ChildItem ${{ inputs.filePattern }}
          ./GitHub/run-task.ps1 -ClientId ${{ secrets.clientid }} -Secret ${{ secrets.secret }} -TenantId ${{ secrets.tenantid }} -FilePattern ${{ inputs.filePattern}} -WorkspaceName ${{ inputs.workspacename }} -Action 'Publish' -Create $false -Overwrite $true

