name: CI-Main-loop
on:
  push:
    branches: [ main ]
  workflow_dispatch:

    
jobs:
  call-workflow-passing-data:
       uses: mahilario-arch/PBI-Deployment-Action/.github/workflows/ci.yml@main
   
       secrets:
        clientid: ${{ secrets.CLIENTID }}
        secret: ${{ secrets.CLIENTSECRET }}
        tenantid: ${{ secrets.TENANTID }}
